### ISSUE TITLE
Error upon launching after npm install and npm start

### ISSUE THREAD

**Issue by scheung38** [DHTMLX/gantt-howto-node#1]
In Mac OSX I already have 

    $ brew services start mysql
 
By default the first error was:

Uncaught TypeError: Cannot read property 'length' of undefined
    at o._parseInner (datastore.js:21)
    at o.parse (treedatastore.js:68)
    at n.t._process_loading (load.js:87)
    at n.t.on_load (load.js:80)
    at n.<anonymous> (load.js:25)
    at ajax.js:118

and subsequently when adding tasks and then refresh:

datastore.js:21 Uncaught TypeError: Cannot read property 'length' of undefined
    at o._parseInner (datastore.js:21)
    at o.parse (treedatastore.js:68)
    at n.t._process_loading (load.js:87)
    at n.t.on_load (load.js:80)
    at n.<anonymous> (load.js:25)
    at ajax.js:118

and tasks are never stored when page is refreshed

Also when adding new tasks:

ajax.js:150 POST http://localhost:1337/data/task net::ERR_CONNECTION_REFUSED

**Comment by AlexKlimenkov** [comment]
Hi,
>By default the first error was:
>Uncaught TypeError: Cannot read property 'length' of undefined

Can you check the server response - https://www.screencast.com/t/AJ510rLJ 
If there is an exception during data loading, you should get an error message in server response:
https://github.com/DHTMLX/gantt-howto-node/blob/master/server.js#L44 , it should give a clue to what's wrong.

Also, do you see any errors in the console/terminal when data loading fails?

**Comment by AlexKlimenkov** [comment]
Closing the issue due to inactivity

**Comment by scheung38** [comment]
Hi @AlexKlimenkov 

The screencast uses AdobeFlash...  

Upon launching I get:

$ npm start

> gantt-node-mysql@1.0.1 start /Users/mincheung/Documents/GitHub/gantt-howto-node
> node server.js

Server is running on port 1337...
{ Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1162:14)
    --------------------
    at Protocol._enqueue (/Users/mincheung/Documents/GitHub/gantt-howto-node/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mincheung/Documents/GitHub/gantt-howto-node/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mincheung/Documents/GitHub/gantt-howto-node/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/mincheung/Documents/GitHub/gantt-howto-node/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/Users/mincheung/Documents/GitHub/gantt-howto-node/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mincheung/Documents/GitHub/gantt-howto-node/node_modules/promise-mysql/lib/helper.js:16:24
    at Promise._execute (/Users/mincheung/Documents/GitHub/gantt-howto-node/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/Users/mincheung/Documents/GitHub/gantt-howto-node/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/mincheung/Documents/GitHub/gantt-howto-node/node_modules/bluebird/js/release/promise.js:79:10)
    at Pool.promiseCallback (/Users/mincheung/Documents/GitHub/gantt-howto-node/node_modules/promise-mysql/lib/helper.js:6:10)
    at pool.query (/Users/mincheung/Documents/GitHub/gantt-howto-node/node_modules/promise-mysql/lib/pool.js:22:28)
    at /Users/mincheung/Documents/GitHub/gantt-howto-node/server.js:28:6
    at Layer.handle [as handle_request] (/Users/mincheung/Documents/GitHub/gantt-howto-node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/mincheung/Documents/GitHub/gantt-howto-node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/mincheung/Documents/GitHub/gantt-howto-node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/mincheung/Documents/GitHub/gantt-howto-node/node_modules/express/lib/router/layer.js:95:5)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true }

**Comment by AlexKlimenkov** [comment]
Hello,

it looks like mysql connection error.
Can you make sure that mysql is running and that it is listening to port 3306, or change the connection settings in server.js
Here is some general info, hope any if it helps
https://stackoverflow.com/questions/30266221/node-js-mysql-error-connect-econnrefused
